#!/bin/sh

set -e

build() {
  rsync -avhL --delete src/ public
  # https://github.com/tdewolff/minify
  minify --recursive --inplace public
}

deploy() {
  rsync -avhL --partial --info=progress2 --delete --info=progress public/ server:/var/www/ormai.me
}

case "$1" in
build) build ;;
deploy)
  build
  deploy
  ;;
serve)
  cd src
  xdg-open http://localhost:8000
  python -m http.server
  ;;
clean) rm -r public;;
*) echo "Unkown subcommand '$1'" ;;
esac
