#!/bin/sh

set -e

readonly SRCDIR=src
readonly OUTDIR=public

build() {
  rsync -avhL --delete "$SRCDIR/" "$OUTDIR"
  # https://github.com/tdewolff/minify
  minify --recursive --inplace public
}

deploy() {
  rsync -avhL --partial --info=progress2 --delete --info=progress "$OUTDIR/" server:/var/www/ormai.me
}

case "$1" in
build) build ;;
deploy)
  build
  deploy
  ;;
serve)
  cd src
  xdg-open http://localhost:8000
  python -m http.server
  ;;
clean) rm -r "$OUTDIR";;
*) echo "Unknown subcommand '$1'" ;;
esac
